### ISSUE TITLE
Fix- I don't know if this project is supported, but the image of the stone is not appearing!

### ISSUE THREAD

**Issue by erickcestari** [datsfilipe/react-jokenpo#11]
![image](https://github.com/datsfilipe/react-jokenpo/assets/96489518/e718e02d-70bb-457d-a4d7-f997f365bafd)

**Comment by datsfilipe** [comment]
hi @erickcestari! I believe this is related to your system fonts, no? I'm on android now and I can see the rock emojis:

![1000019635.jpg](https://github.com/datsfilipe/react-jokenpo/assets/76636791/409d8a0d-ac42-40dd-84bf-9a487e9addef)

**Comment by erickcestari** [comment]
@datsfilipe yes it probably is, I opened the website on Windows 11 without any font configuration, just the default.

**Comment by datsfilipe** [comment]
> @datsfilipe yes it probably is, I opened the website on Windows 11 without any font configuration, just the default.

I see. I have tested on windows 11 too (as you said, without any font configuration) and it still seems fine. So I have no idea what is causing that for you.

**Comment by erickcestari** [comment]
@datsfilipe  ​
Oh, sorry for the mess, In fact, on windows 11 it seems fine.  I have tested on windows 10.

**Comment by datsfilipe** [comment]
> @datsfilipe  ​
> Oh, sorry for the mess, In fact, on windows 11 it seems fine.  I have tested on windows 10.

Yes, I managed to verify it now. Windows 10 seems to have no stone in the emojis font. I don't think it's a problem with the project then.

If I'm wrong, let me know, so I can reopen the issue!
